from .models import Challenge, db


CHALLENGES = [
    {
        "slug": "recon-basics",
        "title": "Local Recon Basics",
        "category": "Recon",
        "difficulty": "Easy",
        "points": 50,
        "description": "Enumerate basic information from your local training target.",
        "objective": "Find the hidden flag inside the local web app homepage comments.",
        "local_target": "http://127.0.0.1:5001",
        "flag": "flag{local_recon_complete}",
    },
    {
        "slug": "web-auth-bypass",
        "title": "Authentication Logic Flaw",
        "category": "Web",
        "difficulty": "Medium",
        "points": 100,
        "description": "Practice finding auth flow mistakes in a sandbox app.",
        "objective": "Exploit the intended lab flaw and recover the dashboard flag.",
        "local_target": "http://127.0.0.1:5001/login-lab",
        "flag": "flag{auth_logic_master}",
    },
    {
        "slug": "idor-training",
        "title": "IDOR Local Challenge",
        "category": "API",
        "difficulty": "Medium",
        "points": 120,
        "description": "Test object authorization weaknesses safely.",
        "objective": "Access a protected resource that should be denied and extract the flag.",
        "local_target": "http://127.0.0.1:5001/api-lab",
        "flag": "flag{idor_hunter}",
    },
    {
        "slug": "xss-context",
        "title": "Stored XSS Context Mapping",
        "category": "Web",
        "difficulty": "Hard",
        "points": 180,
        "description": "Identify payload context and bypass weak filtering in local lab.",
        "objective": "Trigger the payload in admin simulator and capture the generated flag.",
        "local_target": "http://127.0.0.1:5001/xss-lab",
        "flag": "flag{xss_context_ace}",
    },
    {
        "slug": "ssrf-internal",
        "title": "SSRF Internal Service",
        "category": "Infrastructure",
        "difficulty": "Hard",
        "points": 220,
        "description": "Use local SSRF challenge to access non-public internal endpoints.",
        "objective": "Retrieve metadata flag only accessible through server-side request path.",
        "local_target": "http://127.0.0.1:5001/ssrf-lab",
        "flag": "flag{ssrf_path_unlocked}",
    },
    {
        "slug": "subdomain-takeover-sim",
        "title": "Subdomain Takeover Simulation",
        "category": "Recon",
        "difficulty": "Easy",
        "points": 70,
        "description": "Map DNS records in local simulation and identify dangling entries.",
        "objective": "Locate the stale host mapping and capture the ownership proof flag.",
        "local_target": "http://127.0.0.1:5001/recon-lab",
        "flag": "flag{dangling_record_found}",
    },
    {
        "slug": "open-redirect-chain",
        "title": "Open Redirect Chain",
        "category": "Web",
        "difficulty": "Easy",
        "points": 80,
        "description": "Identify unsafe redirect logic in a local login flow simulator.",
        "objective": "Craft a redirect chain that lands on the internal test page with a flag.",
        "local_target": "http://127.0.0.1:5001/redirect-lab",
        "flag": "flag{redirect_chain_complete}",
    },
    {
        "slug": "jwt-none-alg",
        "title": "JWT Validation Weakness",
        "category": "API",
        "difficulty": "Medium",
        "points": 130,
        "description": "Practice token validation testing in a sandbox API.",
        "objective": "Abuse weak JWT validation and retrieve the admin claims flag.",
        "local_target": "http://127.0.0.1:5001/jwt-lab",
        "flag": "flag{jwt_validation_broken}",
    },
    {
        "slug": "rate-limit-bypass",
        "title": "Rate Limit Bypass",
        "category": "API",
        "difficulty": "Medium",
        "points": 140,
        "description": "Assess request throttling controls in a local endpoint.",
        "objective": "Bypass weak rate limiting and unlock the threshold flag.",
        "local_target": "http://127.0.0.1:5001/rate-lab",
        "flag": "flag{rate_limit_bypassed}",
    },
    {
        "slug": "cors-misconfig",
        "title": "CORS Misconfiguration",
        "category": "Web",
        "difficulty": "Medium",
        "points": 120,
        "description": "Verify browser trust boundaries in same-machine lab services.",
        "objective": "Find an overly permissive CORS policy and exfiltrate test data flag.",
        "local_target": "http://127.0.0.1:5001/cors-lab",
        "flag": "flag{cors_policy_unsafe}",
    },
    {
        "slug": "ssti-jinja",
        "title": "SSTI in Jinja Context",
        "category": "Web",
        "difficulty": "Hard",
        "points": 220,
        "description": "Explore template injection detection in controlled environment.",
        "objective": "Trigger server-side template behavior to reveal the hidden flag.",
        "local_target": "http://127.0.0.1:5001/ssti-lab",
        "flag": "flag{jinja_context_escape}",
    },
    {
        "slug": "csrf-state-change",
        "title": "CSRF State Change",
        "category": "Web",
        "difficulty": "Medium",
        "points": 110,
        "description": "Test anti-CSRF controls on local account settings functionality.",
        "objective": "Perform an unauthorized state change and capture response flag.",
        "local_target": "http://127.0.0.1:5001/csrf-lab",
        "flag": "flag{csrf_state_changed}",
    },
    {
        "slug": "blind-sqli-lab",
        "title": "Blind SQLi Practice",
        "category": "Database",
        "difficulty": "Hard",
        "points": 240,
        "description": "Perform boolean/time-based inference in local vulnerable endpoint.",
        "objective": "Extract the secret value and submit the resulting flag.",
        "local_target": "http://127.0.0.1:5001/sqli-lab",
        "flag": "flag{blind_sqli_complete}",
    },
    {
        "slug": "xxe-parser-lab",
        "title": "XXE Parser Behavior",
        "category": "XML",
        "difficulty": "Hard",
        "points": 230,
        "description": "Probe unsafe XML parser settings in a sandbox service.",
        "objective": "Read the controlled local secret file and recover the flag.",
        "local_target": "http://127.0.0.1:5001/xxe-lab",
        "flag": "flag{xxe_file_read_success}",
    },
    {
        "slug": "path-traversal-static",
        "title": "Path Traversal Download",
        "category": "Filesystem",
        "difficulty": "Medium",
        "points": 150,
        "description": "Validate file-serving protections in a local download endpoint.",
        "objective": "Bypass path checks and read the secret flag file.",
        "local_target": "http://127.0.0.1:5001/files-lab",
        "flag": "flag{path_escape_done}",
    },
    {
        "slug": "graph-ql-introspection",
        "title": "GraphQL Introspection Abuse",
        "category": "API",
        "difficulty": "Medium",
        "points": 135,
        "description": "Map schema exposure and discover hidden resolvers.",
        "objective": "Query restricted debug field and capture the returned flag.",
        "local_target": "http://127.0.0.1:5001/graphql-lab",
        "flag": "flag{graphql_hidden_field}",
    },
    {
        "slug": "websocket-authz",
        "title": "WebSocket Authorization",
        "category": "Realtime",
        "difficulty": "Hard",
        "points": 210,
        "description": "Assess message-level authorization for websocket channels.",
        "objective": "Subscribe to unauthorized channel and collect event flag.",
        "local_target": "http://127.0.0.1:5001/ws-lab",
        "flag": "flag{ws_channel_broken_authz}",
    },
    {
        "slug": "race-condition-wallet",
        "title": "Race Condition Wallet",
        "category": "Logic",
        "difficulty": "Hard",
        "points": 250,
        "description": "Test concurrency bugs in transaction processing simulator.",
        "objective": "Double-spend in local wallet lab and trigger the race flag.",
        "local_target": "http://127.0.0.1:5001/race-lab",
        "flag": "flag{race_condition_won}",
    },
    {
        "slug": "host-header-poisoning",
        "title": "Host Header Poisoning",
        "category": "Web",
        "difficulty": "Medium",
        "points": 145,
        "description": "Inspect host-derived URL generation and cache behavior.",
        "objective": "Poison password reset link generation and retrieve the flag.",
        "local_target": "http://127.0.0.1:5001/host-lab",
        "flag": "flag{host_header_poisoned}",
    },
    {
        "slug": "oauth-misconfig-lab",
        "title": "OAuth Redirect Misconfig",
        "category": "Auth",
        "difficulty": "Hard",
        "points": 215,
        "description": "Evaluate local OAuth callback validation logic.",
        "objective": "Abuse redirect URI validation and steal auth code flag.",
        "local_target": "http://127.0.0.1:5001/oauth-lab",
        "flag": "flag{oauth_redirect_exploited}",
    },
    {
        "slug": "request-smuggling-sim",
        "title": "HTTP Request Smuggling Sim",
        "category": "Infrastructure",
        "difficulty": "Hard",
        "points": 260,
        "description": "Study front-end/back-end parser desync in local simulation.",
        "objective": "Smuggle a hidden request and access internal flag response.",
        "local_target": "http://127.0.0.1:5001/smuggle-lab",
        "flag": "flag{parser_desync_success}",
    },
    {
        "slug": "cache-poisoning-lab",
        "title": "Web Cache Poisoning",
        "category": "Infrastructure",
        "difficulty": "Hard",
        "points": 225,
        "description": "Test cache key confusion in a controlled local stack.",
        "objective": "Poison cached response and expose admin flag to normal user.",
        "local_target": "http://127.0.0.1:5001/cache-lab",
        "flag": "flag{cache_poisoned_cleanly}",
    },
    {
        "slug": "prototype-pollution-sim",
        "title": "Prototype Pollution",
        "category": "JavaScript",
        "difficulty": "Medium",
        "points": 160,
        "description": "Explore object merge insecurity in JSON handling pipeline.",
        "objective": "Pollute configuration object and reveal server-side flag.",
        "local_target": "http://127.0.0.1:5001/proto-lab",
        "flag": "flag{prototype_chain_polluted}",
    },
    {
        "slug": "ci-token-leak",
        "title": "CI Secret Exposure",
        "category": "DevSecOps",
        "difficulty": "Easy",
        "points": 90,
        "description": "Review local CI logs for accidental credential exposure.",
        "objective": "Find leaked token in build artifacts and derive the flag.",
        "local_target": "http://127.0.0.1:5001/ci-lab",
        "flag": "flag{ci_secret_recovered}",
    },
]


def seed_challenges():
    for data in CHALLENGES:
        existing = Challenge.query.filter_by(slug=data["slug"]).first()
        if existing:
            existing.title = data["title"]
            existing.category = data["category"]
            existing.difficulty = data["difficulty"]
            existing.points = data["points"]
            existing.description = data["description"]
            existing.objective = data["objective"]
            existing.local_target = data["local_target"]
            existing.flag = data["flag"]
        else:
            db.session.add(Challenge(**data))
    db.session.commit()
